### ISSUE TITLE
Magento 2.3.2 - Error is thrown when navigating to xigen_maintenancepage/maintenance/index/

### ISSUE THREAD

**Issue by mikhail-dubrovskiy** [DominicWatts/MaintenancePage#1]
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "/app/vendor/dominicwatts/maintenancepage/view/adminhtml/ui_component/xigen_maintenancepage_maintenance_listing.xml" is invalid:
Element 'argument': This element is not expected. Expected is ( dataProvider ).
Line: 23

Verify the XML and try again.

Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "/app/vendor/dominicwatts/maintenancepage/view/adminhtml/ui_component/xigen_maintenancepage_maintenance_listing.xml" is invalid:
Element 'argument': This element is not expected. Expected is ( dataProvider ).
Line: 23

Verify the XML and try again.
<pre>#1 Magento\Ui\Config\Reader->read() called at [vendor/magento/module-ui/Config/Data.php:102]
#2 Magento\Ui\Config\Data->initData() called at [vendor/magento/module-ui/Config/Data.php:136]
#3 Magento\Ui\Config\Data->get() called at [vendor/magento/framework/View/Layout/Reader/UiComponent.php:100]
#4 Magento\Framework\View\Layout\Reader\UiComponent->interpret() called at [vendor/magento/framework/View/Layout/ReaderPool.php:105]
#5 Magento\Framework\View\Layout\ReaderPool->interpret() called at [vendor/magento/framework/View/Layout/Reader/Container.php:89]
#6 Magento\Framework\View\Layout\Reader\Container->interpret() called at [vendor/magento/framework/View/Layout/ReaderPool.php:105]
#7 Magento\Framework\View\Layout\ReaderPool->interpret() called at [vendor/magento/framework/View/Page/Config/Reader/Body.php:68]
#8 Magento\Framework\View\Page\Config\Reader\Body->interpret() called at [vendor/magento/framework/View/Layout/ReaderPool.php:105]
#9 Magento\Framework\View\Layout\ReaderPool->interpret() called at [vendor/magento/framework/View/Layout.php:325]
#10 Magento\Framework\View\Layout->generateElements() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:89]
#11 Magento\Framework\View\Layout\Interceptor->generateElements() called at [vendor/magento/framework/View/Layout/Builder.php:129]
#12 Magento\Framework\View\Layout\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Page/Builder.php:55]
#13 Magento\Framework\View\Page\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Layout/Builder.php:65]
#14 Magento\Framework\View\Layout\Builder->build() called at [vendor/magento/framework/View/Page/Config.php:212]
#15 Magento\Framework\View\Page\Config->build() called at [vendor/magento/framework/View/Page/Config.php:235]
#16 Magento\Framework\View\Page\Config->getTitle() called at [vendor/dominicwatts/maintenancepage/Controller/Adminhtml/Maintenance/Index.php:37]
#17 Xigen\MaintenancePage\Controller\Adminhtml\Maintenance\Index->execute() called at [generated/code/Xigen/MaintenancePage/Controller/Adminhtml/Maintenance/Index/Interceptor.php:24]
#18 Xigen\MaintenancePage\Controller\Adminhtml\Maintenance\Index\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#19 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:231]
#20 Magento\Backend\App\AbstractAction->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#21 Xigen\MaintenancePage\Controller\Adminhtml\Maintenance\Index\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#22 Xigen\MaintenancePage\Controller\Adminhtml\Maintenance\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#23 WeltPixel\Backend\Plugin\Utility->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#24 Xigen\MaintenancePage\Controller\Adminhtml\Maintenance\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#25 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#26 Xigen\MaintenancePage\Controller\Adminhtml\Maintenance\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#27 Xigen\MaintenancePage\Controller\Adminhtml\Maintenance\Index\Interceptor->___callPlugins() called at [generated/code/Xigen/MaintenancePage/Controller/Adminhtml/Maintenance/Index/Interceptor.php:39]
#28 Xigen\MaintenancePage\Controller\Adminhtml\Maintenance\Index\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:159]
#29 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:99]
#30 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#31 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#32 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#33 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#34 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:137]
#35 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#36 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#37 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:40]
</pre>

**Comment by DominicWatts** [comment]
Fixed in 1.0.3 release 

https://github.com/DominicWatts/MaintenancePage/releases/tag/1.0.3
